spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: ALWAYS
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    serviceKey1: QPK2FYYEGYCnmqOiScK7tSYuH%2BuEpxXzuAFWVpygOoDdh5rl1%2Foy2fKTrf6riqMDm%2BRnOMWmH9R0Ap2cXharIQ%3D%3D
    serviceKey2: jzJAKYBMgzqWNpqeg4jaT4dW7Ce%2Fdn%2FFUKmQNLOJO1upqH8aRqZINyVkNdLCG5%2B5bdT8aAnzjjQ7%2FIwJH71TIw%3D%3D
  zigbang-api:
    search: https://apis.zigbang.com/v2/search
    aptInfo: https://apis.zigbang.com/apt/danjis

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2